version: '2'
services:
  haproxy:
    image: dockercloud/haproxy:latest
    restart: always
    links:
      - model
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 3031:80
  model:
    image: makingofapg.azurecr.io/vera/annotator:latest
    restart: always